version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing npm dependencies..."
      - npm install

  post_build:
    commands:
      - echo "Decoding the PEM key..."
      - echo "$PEM_KEY" > task.pem  # Use the environment variable directly without base64 decoding
      - chmod 400 task.pem
      - echo "Deploying to server"
      - ssh -o StrictHostKeyChecking=no -i "task.pem" ubuntu@54.198.182.121 'cd /home/ubuntu/express-example/express-main-example && git pull && npm install && pm2 restart index'

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
